### PR TITLE
Fix #804 - Start from Scratch onboarding

### LINKED ISSUE #804: Add "Start from Scratch" template view
Based on the current UI, we are showing this after a user taps on the "Start from Scratch" template:

screen shot 2015-01-27 at 11 56 41 am

### PR DESCRIPTION
**Pull request by alicoding**
still WIP but want to make sure I have something up here first

### CODE REVIEW

**Comment by alicoding** [comment]
@thisandagain R?

**Comment by alicoding** [comment]
or @k88hudson :D

**Comment by thisandagain** [comment]
Couple issues:
- Upon tapping on the "Start from Scratch" template, the user should skip the preview view and go directly to the editor
- After adding your first / any items the CTA should disappear after some period of time (5 seconds?)
- The alignment of the blocks in the `add` screen does not match spec

screen shot 2015-02-12 at 5 34 58 pm
screen shot 2015-02-12 at 5 32 26 pm
screen shot 2015-02-12 at 5 32 13 pm

**Comment by alicoding** [comment]
* Added localization
* Added fade out after 3 seconds with some ease animation
* Skip preview when start from scratch is picked

@thisandagain for the last part I've spoke with @vazquez earlier the day and I think this page needs more work since we have to change all `png` to `svg` and fix the layout which is currently a bit off based on the new spec, so I'm going to skip this one.

**Comment by alicoding** [comment]
@thisandagain R?

**Pull request merged**
