### PR TITLE
Fixes #1240: Add TOS and Privacy Policy links to Profile View

### LINKED ISSUE #1240: Add TOS and Privacy Policy links to Profile View
Until we release to the Google Play and Firefox Marketplace, we need to add a link to our Webmaker TOS and Privacy Policy to the app. My thought is that this can be added to the bottom of the profile view for now and then removed once we release 1.0. TOS and privacy terms are generally handled by the marketplace for mobile apps.

Two small text links (blue) side-by-side should be fine:
```
"Legal" https://webmaker.org/en-US/terms
"Privacy Policy" https://webmaker.org/en-US/privacy
```

@gesa can you take this?

### PR DESCRIPTION
**Pull request by gesa**

### CODE REVIEW

**Comment by thisandagain** [comment]
Doesn't seem like this is using the plugin. After running the URL opens in the same window (Android 5) and I get an `net::ERR_FILE_NOT_FOUND` error after pressing "back".

**Comment by thisandagain** [comment]
Docs available here:
https://github.com/apache/cordova-plugin-inappbrowser/blob/master/doc/index.md

**Comment by thisandagain** [comment]
I can confirm that this slight alternative works on Android 5, Firefox OS 2.0, and Firefox OS 2.1:
```html
<ul class="privacy-legal">
    <li>
        <a onclick="window.open('https://webmaker.org/en-US/terms', '_system');">
            Legal
        </a>
    </li>
    <li>
        <a onclick="window.open('https://webmaker.org/en-US/privacy', '_system');">
            Privacy Policy
        </a>
    </li>
</ul>
```

**Comment by gesa** [comment]
lol so ugly! I'll rewrite the util and give it a v-on so it's not so painful to my standards-obsessed eyes. 👍

**Comment by thisandagain** [comment]
Hehe. :+1:

**Comment by thisandagain** [comment]
One more small note is that the TOS and privacy policy are a little tight to the CTA when the empty state is displayed. Perhaps we could set a `min-height` on the CTA?

screen shot 2015-02-19 at 2 18 14 pm

**Comment by thisandagain** [comment]
R+ :tada:  Awesome. Thanks @gesa

**Pull request merged**
