### PR TITLE
provides SVG versions of all our icons

### PR DESCRIPTION
**Pull request by gesa**
relates to #599, doesn't c-l-o-s-e it though. (afraid to type that word out because automation)

### CODE REVIEW

**Comment by k88hudson** [comment]
Just a couple of things:

* survey.svg is a slightly different blue tint than the rest of the icons
* for some reason, edges of svgs seem to be jagged in android (fine on desktop chrome, firefoxOS)

screenshot_2015-02-18-10-44-46

**Comment by gesa** [comment]
Thanks for the review @k88hudson. I can get on the survey one.

But, what i'm having a really hard time with is, do you have any idea how to improve SVGs on android? It doesn't make any logical sense to me that they're jagged or look pixelated. My internet searches aren't super-helpful. I have a couple hacky ideas but interested in any *real* solutions our collective experience may have.

THEY'RE SCALABLE. VECTOR. GRAPHICS. :angry:

**Comment by gesa** [comment]
I can't even believe [this](https://stackoverflow.com/questions/13457707/blurry-svg-images-in-chrome-for-android/16076247#16076247) works. o_O

**Comment by k88hudson** [comment]
I am still seeing jagged edges on 4.4.2, also on Chrome desktop curriously...  :sob: What if you made the source images twice as large or something?

**Comment by gesa** [comment]
That's so weird, I'm not seeing jagged edges on them anymore. I'll try the resize thing next.

**Comment by gesa** [comment]
Okay, all the SVGs have been simplified, translations have been removed, and sizes have been doubled. Once again, compiled the app and they look great on my phone & in desktop Chrome!

**Comment by k88hudson** [comment]
@gesa Awesome, that fixed it. We should put a note about this Chrome bug somewhere for future reference.

**Comment by k88hudson** [comment]
:ship: it

**Comment by gesa** [comment]
I think it was actually the translations!

**Pull request merged**
