### PR TITLE
In progress: Fix firefox os build

### PR DESCRIPTION
**Pull request by k88hudson**
This fixes almost all issues but a few things left here:

* need fallback for hashbang urls, or a better solution to fix this stuff
* need to remove login, it violates CSP

### CODE REVIEW

**Comment by k88hudson** [comment]
@jbuck R?

**Comment by jbuck** [comment]
@k88hudson r-, looks like you need to fix up some build stuff (LESS and possibly more)

**Comment by k88hudson** [comment]
@jbuck oops sorry, all fixed

**Comment by jbuck** [comment]
@k88hudson r+

**Pull request merged**
