### PR TITLE
Fix #1259 - Rename webmaker-app.json from mobile-appmaker.json

### LINKED ISSUE #1259: Rename Mobile-appmaker.json to Webmaker-app.json
This is an issue because it doesn't match on Transifex

### PR DESCRIPTION
**Pull request by alicoding**
Closes #1259

### CODE REVIEW

**Comment by alicoding** [comment]
@k88hudson R?

**Comment by k88hudson** [comment]
you need to update the unit tests as well in tests/unit

**Comment by alicoding** [comment]
Done @k88hudson. I also updated the app name on our mofo configuration repo to match this new file name, so this should be up as soon as @jdotpz merged my PR :+1:

**Comment by k88hudson** [comment]
Thanks @alicoding !

**Pull request merged**
