### PR TITLE
Fixes #1110:  Cancel type on Delete confirmation dialog looks disabled

### LINKED ISSUE #1110: Cancel type on Delete confirmation dialog looks disabled
Could we make the Cancel word a tad darker?

screenshot 2015-02-12 15 23 13

### PR DESCRIPTION
**Pull request by gesa**
Improved cancel button over #1110 
screen shot 2015-02-13 at 13 03 46

### CODE REVIEW

**Comment by k88hudson** [comment]
@vazquez hm, i feel like the colours are still off here. can you help pick something?

**Comment by gesa** [comment]
@vazquez (ideally one of the existing color variables, or a color based off of the current variables? i.e. `lighten(@color, 15%)` or whatever)

**Comment by vazquez** [comment]
I left a PR on your branch that fixes the colour and some other minor things @gesa

**Comment by gesa** [comment]
Heck yeah, thanks so much @vazquez!!

**Comment by vazquez** [comment]
:boom:

**Comment by k88hudson** [comment]
Awesome, thanks you two :dancers:

**Pull request merged**
