### PR TITLE
Template Updates

### PR DESCRIPTION
**Pull request by thisandagain**
Updated templates for how-to, business (vendor), and blog.

### CODE REVIEW

**Comment by thisandagain** [comment]
@gvn R?

**Comment by gvn** [comment]
Looking good, just a couple things I noticed:

Scrunchy counter (may be kinda unavoidable at this width...)
screenshot 2015-01-27 15 05 05

SVG rendering seems borked on this hero image?
screenshot 2015-01-27 15 38 33

**Comment by thisandagain** [comment]
The counter is def. broken but I could have sworn we had an actual bug to resolve that.

Will check out the SVG rendering issue.

**Comment by thisandagain** [comment]
Fixed the SVG issue. Re-R? @gvn

**Comment by thisandagain** [comment]
@vazquez Re-built asset is available here: https://www.dropbox.com/s/9hv8maoy1k8ddrf/how_to.ai?dl=0

**Comment by gvn** [comment]
R+!

**Pull request merged**
