### PR TITLE
starting a built style guide

### PR DESCRIPTION
**Pull request by gvn**
Related to #1626

### CODE REVIEW

**Comment by gvn** [comment]
This is starting to expose some of the improvements we can make to our reusable components so they work in broader contexts.

(eg: Make Range expand to full width. Remove padding on Tabs and add it contextually.)

My hope is that we can start developing components *in* the style guide view first and then place them into more specific contexts. I've taken that approach on many projects with great results!

CC: @thisandagain @Pomax

**Comment by gvn** [comment]
@xmatthewx I figure this will interest you as well... :dancer: 

styleguide

**Comment by thisandagain** [comment]
:goat: :smile: :panda_face: :cat:

**Comment by xmatthewx** [comment]
heck yes

@vazquez - this can serve as a visual test page to see if future changes funk anything up.

**Comment by gvn** [comment]
Yep, and it'll definitely be a living, growing, and hopefully canonical document!

**Comment by k88hudson** [comment]
Sweet this is awesome. Ring now

**Comment by k88hudson** [comment]
personally i would deemphasize the colour names more since the dark background kinda affects the way you see the adjacent colour but this is awesome, merge away!

**Pull request merged**
