### PR TITLE
making color picker header consistent

### LINKED ISSUE #645: Make consistent title bar UI in Brick Options and Colorpicker screen
Right now the colorpicker has a "<" 
image

Brick edit screen has Save & Cancel
image

Let's make them both Save & Cancel or Done & Cancel so they are consistent.

### PR DESCRIPTION
**Pull request by gvn**
closes #645

### CODE REVIEW

**Comment by thisandagain** [comment]
@gvn Post-holiday bump :christmas_tree: :cake: :cat2:

**Comment by gvn** [comment]
@thisandagain I'm not getting any errors when I run `gulp lint` locally and that Travis details link seems to have expired. Any ideas?

**Comment by thisandagain** [comment]
Gah! Because it changed orgs ... mind bumping the commit to get travis to re-run?

**Comment by gvn** [comment]
I'm gonna merge despite Travis's objections because it appears to be borked.

**Pull request merged**
