### PR TITLE
force close shim on navigation change

### LINKED ISSUE #1324: Edit background overlay remains visible if dismissed using back button on phone
*OS:* Android 5.0.1

**Repro Steps:**
1. make blog app
2. edit picture
3. press phone's back button

**Expected:** dialog dismissed
**Actual:** image edit tool disappears, but the dark overlay remains

### PR DESCRIPTION
**Pull request by gvn**
Resolves #1324

### CODE REVIEW

**Comment by gvn** [comment]
I don't have a 5.0.1 device and wasn't able to repro on 4.2. However, this patch should force the shim to close on nav change.

**Comment by cadecairos** [comment]
nope, still seeing the shim

**Comment by cadecairos** [comment]
nvm, I uninstalled, reinstalled to check. seems to work.

The back button behaviour in the app feels weird though. instead of closing the edit dialog only, it closes and navigates to a different part of the app.

**Comment by gvn** [comment]
Suggest filing a follow up bug for discussion of the back behavior so we can get this merged...cool?

**Comment by cadecairos** [comment]
:+1:

**Pull request merged**
