### PR TITLE
[#674] Add image picker editor

### PR DESCRIPTION
**Pull request by k88hudson**
Ok so this is working pretty well. Right now it allows you to enter an image url, or take a picture from camera or gallery; it just saves the data uri directly to the `source` value right now. We can implement storing locally later

### CODE REVIEW

**Comment by k88hudson** [comment]
R @jbuck ?

**Comment by k88hudson** [comment]
(Requires https://github.com/k88hudson/webmaker-app-cordova/commit/3ff22084b1701662c18119e5389a4d45e7237714)

**Comment by k88hudson** [comment]
Actually @thisandagain can you take a look at this? i had to do some UI for choosing photo/gallery

**Comment by thisandagain** [comment]
:smile: OMG ... so excited. Thanks @k88hudson R+

**Pull request merged**
