### PR TITLE
[#1001] Update firebase urls for staging

### PR DESCRIPTION
**Pull request by k88hudson**

### CODE REVIEW

**Comment by k88hudson** [comment]
Needs to be merged simultaneously with https://github.com/mozilla/webmaker-app-publisher/pull/13/files

**Comment by k88hudson** [comment]
R @simonwex ?

**Comment by k88hudson** [comment]
or @thisandagain

**Comment by thisandagain** [comment]
R+ but let's hold off on merging until #1193 lands.

**Comment by k88hudson** [comment]
Sounds good to me

**Pull request merged**
