### PR TITLE
Map Block Issue#283

### PR DESCRIPTION
**Pull request by JordanTheriault**
Solves issue #283 Map Block implementation.

This adds Leaflet.js to the block and grabs tiles from the MapQuest tile server which is free to use for applications.

Currently it locates by use of longitude and latitude attributes in the brick data. The address and location name will be displayed in a popup which comes up during initial load, or when the marker is clicked.

### CODE REVIEW

**Comment by thisandagain** [comment]
@JordanTheriault Hey Jordan! Are you still interested in finishing this up?

**Comment by JordanTheriault** [comment]
Yes, I am, just back from vacation today. I will look into it. Thank you!

**Comment by thisandagain** [comment]
Hey @JordanTheriault just holler if you'd like some help finishing this up. You can find me in the #webmaker IRC channel (i'm on PST time).

**Comment by JordanTheriault** [comment]
Working on my end, but failing Travis CI, any insight @thisandagain ?

**Comment by JordanTheriault** [comment]
Found the issue as being with Browserify eliminating "this" as the global as described in [this](https://github.com/substack/node-browserify/issues/372) but I'm still looking for a solution to it.

**Comment by thisandagain** [comment]
Gotcha. Best practice when working with browserify is to use `global` instead of `window`.

**Comment by thisandagain** [comment]
I'm going to close this pending some major design changes in the pipeline right now. Checkout the milestone (https://github.com/mozilla/webmaker-app/milestones/Prototypes) for more details. Still very interested in this though ... if you'd like to connect just send me a note on IRC. Happy to discuss!

**Pull request closed without merging**
