### PR TITLE
Image editor ui

### PR DESCRIPTION
**Pull request by k88hudson**

### CODE REVIEW

**Comment by k88hudson** [comment]
Note: PR in progress to fix cordova camera code for firefoxos https://github.com/k88hudson/cordova-plugin-camera/compare/apache:master...master

**Comment by k88hudson** [comment]
R @thisandagain?

**Comment by thisandagain** [comment]
Needs the upstream changes to `webmaker-app-cordova` to be landed prior to R?

**Comment by k88hudson** [comment]
@thisandagain https://github.com/mozilla/webmaker-app-cordova/pull/24

**Comment by thisandagain** [comment]
On FFOS we should feature / agent detect and only show the "Gallery" / "Photo" picker on Android.

**Comment by thisandagain** [comment]
On Android the image compression settings are quite a bit too high.

**Comment by k88hudson** [comment]
@thisandagain ffos UI issue resolved, although the image quality setting seems to not be recognized by android. need to find out why

**Comment by k88hudson** [comment]
@thisandagain so it seems that there's something wrong with the plugin code that makes it always read quality (on the JS side) as `50`.

**Comment by k88hudson** [comment]
Filed https://github.com/mozilla/webmaker-app/issues/1025

**Comment by thisandagain** [comment]
R+ :basketball:

**Pull request merged**
