### PR TITLE
Fixes #765:  Rename spinner block to counter

### LINKED ISSUE #765: Rename spinner block to counter
Just the folder name. since... that's what it is.

### PR DESCRIPTION
**Pull request by gesa**

### CODE REVIEW

**Comment by thisandagain** [comment]
You'll want to add `counter` to the `views/add/index.js` file as it currently is still referencing the old "spinner" component.

**Comment by gesa** [comment]
Good catch! I actually also found a miss in tests and in templates. Thank you!

**Comment by thisandagain** [comment]
Awesome. Thanks @gesa ! R+

**Comment by thisandagain** [comment]
Mind rebasing / merging on top of your other patch?

**Pull request merged**
