### PR TITLE
Fixes #975: Phone Call Button should have color pref

### LINKED ISSUE #975: Phone Call Button should have color pref
no reason why it should be so deprived.

### PR DESCRIPTION
**Pull request by gesa**
@davidascher just for you. so the buttons can be happy.

### CODE REVIEW

**Comment by gvn** [comment]
Blocked by #1048

**Comment by thisandagain** [comment]
@gvn @gesa This should now be un-blocked.

**Comment by thisandagain** [comment]
@gesa Could you please pull from upstream?

**Comment by gesa** [comment]
Done! All yours, @gvn

**Comment by thisandagain** [comment]
R+ :+1: :rotating_light: :octocat:

**Pull request merged**
