### PR TITLE
Fix #1367 - Edit app page is empty

### LINKED ISSUE #1367: Edit app page is empty
STR:

1. Open the app
2. Go to "Make" tab
3. Choose "Start from Scratch"
4. Click the gear button

Expected: 
To see the edit title and the logo maker

Actual result:

Blank

screen shot 2015-02-26 at 11 40 19

### PR DESCRIPTION
**Pull request by alicoding**
Closes #1367

### CODE REVIEW

**Comment by alicoding** [comment]
This was caused by https://github.com/mozilla/webmaker-app/commit/d9cd189d56822ff0c07fc08642d4ce6fafea2368 which we were trying to remove the scroll bar. I'm removing the padding when there is no block which is what we intended to make.

**Comment by alicoding** [comment]
@thisandagain R?

**Comment by thisandagain** [comment]
The settings view now loads, but the margins are incorrect / do not match settings everywhere else.

**Comment by alicoding** [comment]
Good catch @thisandagain !!!

**Comment by thisandagain** [comment]
R+ :floppy_disk:

**Pull request merged**
