### PR TITLE
2 steps back after adding new block

### PR DESCRIPTION
**Pull request by gvn**
Right now after you add a block you'll go back to the choose a block screen. This should prevent that.

I know it's kind of gross, but it's a band aid until we can rewrite navigation... :ambulance:

### CODE REVIEW

**Comment by thisandagain** [comment]
Related to a larger set of back button issues here: https://github.com/mozilla/webmaker-app/issues/1365

**Comment by gvn** [comment]
Resolves #1365

**Comment by k88hudson** [comment]
Right now this is what I'm observing:

```
NOT OK
app editor > edit block > cancel > back button (or android back)
app editor > add block > choose block > cancel
app editor > add block > choose image > back button (or android back)
app editor > add block > choose text > done
app editor > edit block > colour picker > done or cancel > done > back button

OK:
app editor > edit block > done > back button (or android back)
app editor > edit block > colour picker > done or cancel > done > back button
```

**Comment by thisandagain** [comment]
Confirmed on Nexus 5 running 5.0.1

**Comment by gvn** [comment]
Ok, all those STR should work now! :+1:

**Comment by thisandagain** [comment]
Dang! :smile:

**Pull request merged**
