### PR TITLE
Fix #671 - Rename input to text box

### LINKED ISSUE #671: Rename "input" block to "text box"
Research suggested no one understands what "input" means here:

image

Any suggestions @xmatthewx @cassiemc @vazquez ?

### PR DESCRIPTION
**Pull request by k88hudson**
@gvn R?

### CODE REVIEW

**Comment by k88hudson** [comment]
or @vazquez R

**Comment by gvn** [comment]
If those strings don't need to be localized then R+

**Comment by vazquez** [comment]
:+1:

**Comment by k88hudson** [comment]
@gvn good catch

**Pull request merged**
