### PR TITLE
adding inlineEditor component

### PR DESCRIPTION
**Pull request by gvn**
R? @k88hudson

### CODE REVIEW

**Comment by k88hudson** [comment]
This is AWESOME way to go. A few little things:

* transition on background fading to black feels a tad slow to me, maybe speed up by 100ms.
* unfortunately css is busted on the buttons on 4.2. Seems to be a weird thing with flexbox where you need to declare children as block (inline/inline-block won't work). adding `display: block; text-align: center` should do the job
* the designs have a 3 or 4px border radius on the bottom left and right corners
* moving elements is too jarring, needs a transition. happy to file as a new ticket

screenshot_2015-02-02-11-17-45

**Comment by gvn** [comment]
Thanks! 

I took care of the first 3 points, but yeah, if we can file another ticket for refining the post-edit transitions that'd be awesome. :metal: 

R? @k88hudson

**Comment by thisandagain** [comment]
Feel free to drop the animation / transition tickets into the UI improvements milestone. :smile:

**Comment by k88hudson** [comment]
Nice looks good R+

**Comment by gvn** [comment]
Filed follow on ticket #875

**Pull request merged**
