### PR TITLE
Fix #1312 - Enable Hindi locale

### LINKED ISSUE #1312: Hindi not in the list under Developer Health Check > CURRENT_LANG
I downloaded and installed the app from http://mzl.la/installwm But Hindi is not listed under Developer Health Check > CURRENT_LANG. 

I even changed my phone's locale to Hindi, but still could not see Hindi listed in the CURRENT_LANG.
My phone is running Android 4.4.4 and a Cynogenmod Kernel.

### PR DESCRIPTION
**Pull request by alicoding**
Closes #1312

### CODE REVIEW

**Comment by alicoding** [comment]
@k88hudson R?

**Comment by thisandagain** [comment]
I'm not sure if it's related to this patch, but while testing I found a fairly serious issue.

STR:
- Launch app
- Open developer menu
- Change language to Hindi
- Close developer menu
- Try to change tabs

Result:
```
ReferenceError: नाम is not defined
index.js:16104:0
```

**Comment by thisandagain** [comment]
I can confirm that this does not happen with `french`.

**Comment by alicoding** [comment]
It is an error on Translation directly, so this is now fixed on Transifex and it should be updated once we do another pull again (in an hour).

**Comment by thisandagain** [comment]
Thanks @alicoding !

**Pull request merged**
