### PR TITLE
universal 'save' button styling

### PR DESCRIPTION
**Pull request by Pomax**
note: not hooked up yet, since that's part of a different ticket.

### CODE REVIEW

**Comment by Pomax** [comment]
shows up in the make title edit view and the color picker

**Comment by alicoding** [comment]
I think you need to remove `<button class="btn btn-block" v-on="click: onSave">{{ 'Save' | i18n}}</button>` from `views/block/index.html` too

**Comment by Pomax** [comment]
different issue - this is for implementing the styling only

**Comment by vazquez** [comment]
R+ for styling! :ear:

**Pull request merged**
