### PR TITLE
Fix html rendering for sign-in #797

### PR DESCRIPTION
**Pull request by pippinlee**
preview preview preview

### CODE REVIEW

**Comment by thisandagain** [comment]
:smile: Thanks @pippinlee !

**Comment by thisandagain** [comment]
@alicoding R?

**Comment by alicoding** [comment]
Thanks for the fix @pippinlee but can I ask you to change it to this if you don't mind? 

``` html
<h1><span v-bind-html="'Make and share the web' | i18n"></span></h1>
```

**Comment by pippinlee** [comment]
Hey @alicoding, speaking with @k88hudson, she explained that we likely don't need to include the `| i18n` filter because `v-bind-html` already runs the keys through `i18n`.

Have updated the PR without the `i18n` filter, but will happily change it back if you think we should keep it.

**Comment by alicoding** [comment]
I'm okay with both keeping it or not, but I prefe we do which will help us know that these are being localized (though just v-bind-html still can tell the same) but I guess it just nice to see it when we need to look through? So ill let you decide here :)

**Comment by pippinlee** [comment]
Good ideas!

Agree that using `v-bind-html` and explicitly including the `i18n` filter helps with understanding what is happening. Balancing that with #803, it may make sense to just change the directive name so that this is clearer down the road.

For this PR let's do without it, and then what I've done is updated this PR with more details in the docs. It should hopefully help clarify the use of this custom directive.

If I'm missing anything let me know 👍

**Comment by alicoding** [comment]
I like this! Lets land this one then update the directive name to be more explicit about `i18n` as suggested in the next PR. r+ [[unflagged]](http://plzkthx.herokuapp.com)

**Comment by thisandagain** [comment]
:+1:

**Comment by alicoding** [comment]
Not sure how to unflag my request here on plzthx hehe @thisandagain sorry for the noise here but just trying to get that off.

**Comment by davidascher** [comment]
@alicoding: in plzkthx if your'e signed in you should have a trash icon
next to the mention.

**Comment by alicoding** [comment]
@davidascher It is now gone, but this one was the only one without trash icon :(

**Comment by davidascher** [comment]
i'll probably kill plzkthx.  Let me know if  you find this kind of bug on
the build.webmaker.org site when logged in.

**Comment by alicoding** [comment]
@davidascher sure will do. Right now they are both gone on build and plzthnx

**Pull request merged**
