### PR TITLE
Unifying the blue colours. 

### LINKED ISSUE #1113: Three slightly different blues
I count three large expanses of three slightly different blues:
 - the header
 - the background of the image in the teacher app
 - the submit button

I suggest making them the same or more than just a JND apart (more vision jargon)

### PR DESCRIPTION
**Pull request by vazquez**
Fixes #1113

### CODE REVIEW

**Comment by thisandagain** [comment]
The alignment of the submit button is a little off (not following margins used by other components in the editor):

screenshot_2015-02-19-13-19-14

**Comment by thisandagain** [comment]
*Really* close. One small remaining issue with the "√" alignment and "complete" states of the submit button component:
screen shot 2015-02-24 at 12 11 57 am
screen shot 2015-02-24 at 12 12 04 am

**Comment by Pomax** [comment]
for the placeent I think we can use a `calc(10% - 15px + 0.5em)`, to effect half the width of the `::before` shaded section (10%) compensated for the 15 px padding and width of the checkmark.

**Comment by Pomax** [comment]
I've filed https://github.com/vazquez/webmaker-app/pull/1 against ricardo's branch, which adds in the checkmark repositioning; merging that into ricardo's branch should auto-update this PR, too.

**Comment by vazquez** [comment]
We are good to go! :racehorse: 

The issues with "√" alignment and "complete" states of the submit button component have been addressed.

**Comment by vazquez** [comment]
After a quick look around, I did not end up going with `calc` due to the lack of support in Android 4.2.

**Comment by vazquez** [comment]
Always centered no matter the size:

screenshot 2015-02-25 23 28 17

screenshot 2015-02-25 23 28 25

Submitted state:

screenshot 2015-02-25 23 29 25

**Comment by thisandagain** [comment]
R+ :smile:

**Pull request merged**
