### PR TITLE
Updating edit icon and colour. Fixes #1036

### LINKED ISSUE #1036: Update Edit Icon
In the Editor, the edit icon looks like this:

screenshot 2015-02-11 18 09 37

We no longer use that blue, so we need to update it.

screenshot 2015-02-11 18 10 51

The new icon currently resides in Google Drive > WMA > GUI > Icons > edit.svg

### PR DESCRIPTION
**Pull request by vazquez**

### CODE REVIEW

**Comment by vazquez** [comment]
screenshot 2015-02-17 10 02 04

**Comment by k88hudson** [comment]
@vazquez  I merged in https://github.com/mozilla/webmaker-app/pull/1180 with a few tweaks. Thanks!! :dancer:

**Comment by k88hudson** [comment]
ooops sorry wrong PR

**Comment by k88hudson** [comment]
R+ looks waaayy nicer :dancer:

**Pull request merged**
