### PR TITLE
Fix reliability issues with network library

### PR DESCRIPTION
**Pull request by thisandagain**
This should resolve https://github.com/mozilla/webmaker-app/issues/1190 and help with testing for #1224

### CODE REVIEW

**Comment by thisandagain** [comment]
@k88hudson R?

/cc @gesa @alicoding

**Comment by k88hudson** [comment]
Interesting. This looks fine to me, although I wonder if this might be a case where using the device ready event might be helpful? http://docs.phonegap.com/en/4.0.0/cordova_events_events.md.html#deviceready

**Comment by k88hudson** [comment]
If you decide to use the `deviceready` event, throw back on me for a re-R just so i can give it a test on both devices

**Comment by thisandagain** [comment]
Good call. Updated and checked on Android 5.0 and Firefox OS 2.0.0-prerelease

**Comment by alicoding** [comment]
Tested on Android 4.4 and this is working perfectly :) :+1:

**Comment by k88hudson** [comment]
:dancer: awesome!

**Pull request merged**
