### PR TITLE
close menu with leftswipe

### LINKED ISSUE #950: Left swipe should dismiss side menu
STRs:

 - tap hamburger button
 - madly swipe left to dismiss the sidebar

### PR DESCRIPTION
**Pull request by Pomax**
fixes #950

### CODE REVIEW

**Comment by gvn** [comment]
R-
 [[unflagged]](http://plzkthx.herokuapp.com)

This doesn't seem to be working on Android (tried on Nexus), but it seems to work on FFOS.

**Comment by Pomax** [comment]
http://stackoverflow.com/questions/16873981/how-to-use-hammer-to-swipe might be related, will try tomorrow

**Comment by Pomax** [comment]
updated the constructor to be android-friendly (probably a pixel density issue)

**Comment by thisandagain** [comment]
Yesssssss. Works. R+ :hammer:

**Pull request merged**
