### PR TITLE
Clean up Router & Add documentation

### PR DESCRIPTION
**Pull request by ryanw-ny**
Modifications:
  * Now supports both static and OOP implementations 
  * Ability to manipulate the router across classes
  * Complete documentation, for both implementations
  * Cleaned up the code, made it easier to read
  * Removed bulk, simplified methods, global context

Documentation can also be read here: https://github.com/ryanw-ny/routable

### CODE REVIEW

**Comment by ryanw-ny** [comment]
@thisandagain How do things look so far? Eager to get some feedback and possibly get this accepted!

**Comment by ryanw-ny** [comment]
Closing this because there seems to be no intention on getting this pulled, will reopen if requested.

**Comment by thisandagain** [comment]
Hey @ryanw-ny , I've been traveling and am just catching up this week. I'll take a look at this tomorrow.

**Comment by ryanw-ny** [comment]
@thisandagain Great, thanks! :dolphin:

**Comment by thisandagain** [comment]
Awesome work @ryanw-ny . R+ :+1:

**Pull request merged**
