### PR TITLE
Fix #1252 - Cancel shouldn't add block to my app

### LINKED ISSUE #1252: Cancel on adding block page shouldn't add a block
STR:

1. Click "Make" tab
2. Choose "Start From Scratch"
3. Tap the "+" sign
4. Choose "Text" block
5. Tap "Cancel" on top left

Expected:
Shouldn't add Text block to my app

What happen:
Text block was added to my app

### PR DESCRIPTION
**Pull request by alicoding**
Closes #1252 

And should also fix https://github.com/mozilla/webmaker-app/issues/956

### CODE REVIEW

**Comment by alicoding** [comment]
@k88hudson R?

**Comment by k88hudson** [comment]
Nice!

**Comment by k88hudson** [comment]
actually, let me test one more thing

**Comment by k88hudson** [comment]
This only works for the case of adding a new block; if an existing block is added, and cancel is pressed, it should just cancel the edits, not remove the block. In this case, it should also return to the /make screen, not /add.

**Comment by alicoding** [comment]
@k88hudson based on this ticket though https://github.com/mozilla/webmaker-app/issues/956 they are suggesting we are going back to /add since the user might not finish adding or still exploring each block that they are trying to add.

**Comment by alicoding** [comment]
@k88hudson I might have to go back and look at it again, but at the time when I worked on this bug I felt like the block was added immediately and as they modify the block then we update it in the object.

**Comment by k88hudson** [comment]
@alicoding going back to /add makes sense after adding and then cancelling a block, but not after editing an existing block and then pressing cancel. So to be clear, your implementation is 100% correct for the "new block" case, but not for the edit an old block case. Make sense?

**Comment by alicoding** [comment]
@k88hudson Oh! I didn't test on modifying the block! Oops! Now I have to make sure I cover this part...

**Comment by alicoding** [comment]
@k88hudson what do you think of this?

**Comment by k88hudson** [comment]
@alicoding mind doing a quick rebase?

**Comment by alicoding** [comment]
@k88hudson done :)

**Comment by thisandagain** [comment]
Great. Thanks @alicoding

**Pull request merged**
